name: Build and push

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: runner_image
    steps:
      - name: Checkout
        run: /scripts/clone.sh ${{ gitea.server_url }} ${{ gitea.repository }}
      
      - name: Run CI script - install dependencies and compile
        run: /run_dir/ci.sh

      - name: Push to Gitea release
        run: /scripts/push-gitea.sh ${{ secrets.RELEASE_TOKEN }} ${{ gitea.repository }} ${{ gitea.ref_name }} /target/keycloak-altcha-jar-with-dependencies.jar

